version: "3.9"
services:
  development-environment:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes: 
      - ./curators:/stews/curators
      - ./scripts:/stews/scripts
      - ./source:/stews/source
